version: '3.8'

services:
  postgres:
    build:
        context: ./smart_home
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGUSER=postgres
    networks:
      - smarthome-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "smarthome"]
      interval: 1s
      timeout: 1s
      retries: 5

  temperature-api:
    container_name: temperature-api
    hostname: temperature-api
    build:
      context: ./smarthome-api
      dockerfile: smarthome-api/Dockerfile
    ports:
      - "8081:8081"
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    hostname: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/smarthome"
      TEMPERATURE_API_URL: "http://temperature-api:8081"
    ports:
      - "8082:8082"
    restart: unless-stopped
    networks:
      - smarthome-network

  sensor-api:
    container_name: sensor-api
    hostname: sensor-api
    depends_on:
      app:
        condition: service_started
    build:
      context: ./sensor-api
      dockerfile: sensor-api/Dockerfile
    ports:
      - "8083:8083"
    networks:
      - smarthome-network

  telemetry-api:
    container_name: telemetry-api
    hostname: telemetry-api
    depends_on:
      app:
        condition: service_started
    build:
      context: ./telemetry-api
      dockerfile: telemetry-api/Dockerfile
    ports:
      - "8084:8084"
    networks:
      - smarthome-network

  proxy-api:
    container_name: proxy-api
    depends_on:
      app:
        condition: service_started
      sensor-api:
        condition: service_started
      telemetry-api:
        condition: service_started
    build:
      context: ./proxy-api
      dockerfile: proxy-api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - smarthome-network
    environment:
      REDIRECT_PERCENT: "50"
      TEMPERATURE_API_URL: "http://smarthome-app:8082"
      SENSOR_API_URL: "http://sensor-api:8083"
      TELEMETRY_API_URL: "http://telemetry-api:8084"

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge